-- SUPABASE POSTGRESQL MIGRATION FOR LAB BIOLOGI SMANSA PINRANG

DROP TABLE IF EXISTS log_riwayat CASCADE;
DROP TABLE IF EXISTS peminjaman CASCADE;
DROP TABLE IF EXISTS barang CASCADE;
DROP TABLE IF EXISTS admin CASCADE;


CREATE TABLE admin (
  id BIGSERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  nama_lengkap TEXT NOT NULL,
  nip TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE barang (
  id BIGSERIAL PRIMARY KEY,
  kode_barang TEXT,
  nama_barang TEXT NOT NULL,
  spesifikasi TEXT,
  kategori TEXT NOT NULL,
  sub_kategori TEXT,
  stok_total INTEGER NOT NULL DEFAULT 0,
  stok_tersedia INTEGER NOT NULL DEFAULT 0,
  stok_rusak INTEGER NOT NULL DEFAULT 0,
  satuan TEXT DEFAULT 'Buah',
  kondisi TEXT DEFAULT 'Baik',
  lokasi_penyimpanan TEXT,
  sumber_dana TEXT,
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE peminjaman (
  id BIGSERIAL PRIMARY KEY,
  nomor_formulir TEXT,
  barang_id BIGINT NOT NULL,
  nama_peminjam TEXT NOT NULL,
  kelas_jabatan TEXT,
  keperluan TEXT,
  jumlah INTEGER NOT NULL,
  tanggal_pinjam DATE NOT NULL,
  tanggal_rencana_kembali DATE,
  tanggal_kembali_aktual DATE,
  kondisi_saat_pinjam TEXT DEFAULT 'Baik',
  kondisi_saat_kembali TEXT,
  status TEXT NOT NULL DEFAULT 'dipinjam',
  keterangan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE log_riwayat (
  id BIGSERIAL PRIMARY KEY,
  jenis_aktivitas TEXT NOT NULL,
  barang_id BIGINT,
  peminjaman_id BIGINT,
  deskripsi TEXT NOT NULL,
  admin_name TEXT NOT NULL,
  waktu TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_barang_kategori ON barang(kategori);
CREATE INDEX idx_barang_nama ON barang(nama_barang);
CREATE INDEX idx_peminjaman_status ON peminjaman(status);
CREATE INDEX idx_log_waktu ON log_riwayat(waktu DESC);
INSERT INTO admin (username, password_hash, nama_lengkap, nip) VALUES ('admin', '$2a$10$TDC.YHcXtn7stqAXFHAbTum8qrTBh0Bebtcf8SF7sB.gLNUqiO6qm', 'Juni Aswati, S.Si (Laboran Lab Biologi)', '19681231 199203 2 095');

INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (1, 'KGE 11/1000', 'Gelas Kimia', '1000 ml', 'Alat Bahan Kaca', 'Berskala', 9, 9, 2, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 1', 'A, D', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (2, 'KGE 11/600', 'Gelas Kimia', '600 ml', 'Alat Bahan Kaca', 'Berskala', 1, 1, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (3, 'KGE 11/500', 'Gelas Kimia', '500 ml', 'Alat Bahan Kaca', 'Berskala', 10, 10, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (4, 'KGE 11/250', 'Gelas Kimia', '250 ml', 'Alat Bahan Kaca', 'Berskala', 10, 10, 1, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 1', 'C', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (5, 'KGE 11/100', 'Gelas Kimia', '100 ml', 'Alat Bahan Kaca', 'Berskala', 9, 9, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (6, 'KGE 11/50', 'Gelas Kimia', '50 ml', 'Alat Bahan Kaca', 'Berskala', 12, 12, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (7, 'KLA 45/250', 'Erlemeyer', '250 ml', 'Alat Bahan Kaca', 'Berskala', 8, 8, 0, 'Buah', 'Baik', 'Lemari 3 / 2', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (8, 'KLA 45/100', 'Erlemeyer', '100 ml', 'Alat Bahan Kaca', 'Berskala', 2, 2, 0, 'Buah', 'Baik', 'Lemari 3 / 2', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (9, '', 'Erlemeyer', '500 ml', 'Alat Bahan Kaca', 'Berskala', 3, 3, 0, 'Buah', 'Baik', 'Lemari 3 / 2', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (10, '', 'Psychrometer Piche', 'Model Pich', 'Alat Bahan Kaca', 'Berskala', 0, 0, 0, 'Buah', 'Baik', 'Lab Biologi', '-', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (11, '', 'Gelas ukur', '250 ml', 'Alat Bahan Kaca', 'Berskala', 0, 0, 0, 'Buah', 'Baik', 'Lab Biologi', '-', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (12, '', 'Gelas ukur', '100 ml', 'Alat Bahan Kaca', 'Berskala', 0, 0, 0, 'Buah', 'Baik', 'Lab Biologi', '-', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (13, 'KSL 40/50', 'Gelas ukur', '50 ml', 'Alat Bahan Kaca', 'Berskala', 5, 5, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (14, 'KSL 40/25', 'Gelas ukur', '25 ml', 'Alat Bahan Kaca', 'Berskala', 0, 0, 0, 'Buah', 'Baik', 'Lab Biologi', '-', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (15, 'KSL 40/10', 'Gelas ukur', '10 ml', 'Alat Bahan Kaca', 'Berskala', 1, 1, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (16, 'KTE 20', 'Termometer', 'Pratikum', 'Alat Bahan Kaca', 'Berskala', 20, 20, 4, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 4', 'A,D', '4 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (17, 'BFS 62', 'Potometer', 'Buah', 'Alat Bahan Kaca', 'Berskala', 1, 1, 3, 'Buah', 'Sebagian Rusak', 'Lemari 9 / 2', 'A', '3 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (18, 'BGE 48', 'Soil Capillarity APP', 'Set', 'Alat Bahan Kaca', 'Berskala', 5, 5, 3, 'Set', 'Sebagian Rusak', 'Lemari 9 / 3', 'A,B', '3 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (19, 'KAS 01', 'Stopwacth', 'iaksuv', 'Alat Bahan Kaca', 'Berskala', 3, 3, 0, 'Buah', 'Baik', 'Lemari 4/1', 'C,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (20, 'BFS 74', 'Respirometer', 'Set', 'Alat Bahan Kaca', 'Berskala', 7, 7, 0, 'Set', 'Baik', 'Lemari 4/1', 'A,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (21, '', 'Termometer', 'kaca', 'Alat Bahan Kaca', 'Berskala', 0, 0, 0, 'Buah', 'Baik', 'Lab Biologi', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (22, '', 'Termometer', 'Ruang', 'Alat Bahan Kaca', 'Berskala', 3, 3, 0, 'Buah', 'Baik', 'Lemari 4/1', 'E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (23, 'KKA 25/075', 'Gelas Arloji', 'Kecil', 'Alat Bahan Kaca', 'Tidak Berskala', 78, 78, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (24, 'KKA 25/150', 'Gelas Arloji', 'Besar', 'Alat Bahan Kaca', 'Tidak Berskala', 42, 42, 0, 'Buah', 'Baik', 'Lemari 3 / 1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (25, 'KTA 14/025', 'Tabung Sampel', 'Buah', 'Alat Bahan Kaca', 'Tidak Berskala', 28, 28, 1, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 1', 'B', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (26, 'VKBS 28', 'Bunsen', 'Buah', 'Alat Bahan Kaca', 'Tidak Berskala', 13, 13, 5, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 2', 'F', '5 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (27, 'KCR 15/100', 'Corong', '100 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 4, 4, 0, 'Buah', 'Baik', 'Lemari 3 / 3', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (28, 'KCR 15/90', 'Corong', '90 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 1, 1, 1, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 3', 'A', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (29, 'KCR 15/75', 'Corong', '75 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 10, 10, 0, 'Buah', 'Baik', 'Lemari 3 / 3', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (30, 'KSP 12', 'Batang Pengaduk', 'Pende', 'Alat Bahan Kaca', 'Tidak Berskala', 26, 26, 1, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 3', 'A,D', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (31, 'KSP 12', 'Batang Pengaduk', 'Panjang', 'Alat Bahan Kaca', 'Tidak Berskala', 13, 13, 0, 'Buah', 'Baik', 'Lemari 3 / 3', 'B,E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (32, '', 'Ose Bulat', 'Batang', 'Alat Bahan Kaca', 'Tidak Berskala', 21, 21, 0, 'Batang', 'Baik', 'Lemari 3 / 3', 'E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (33, 'KPP 70', 'Pipet Tetes', 'kecil', 'Alat Bahan Kaca', 'Tidak Berskala', 13, 13, 4, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 3', 'D', '4 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (34, 'KPP 70', 'Pipet Tetes', 'Besar', 'Alat Bahan Kaca', 'Tidak Berskala', 35, 35, 30, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 3', 'D', '30 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (35, 'KCA 45', 'Cawan Petri', 'Pasang', 'Alat Bahan Kaca', 'Tidak Berskala', 21, 21, 0, 'Pasang', 'Baik', 'Lemari 3 / 4', 'B, G', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (36, '', 'Tabung Reaksi', 'Kecil', 'Alat Bahan Kaca', 'Tidak Berskala', 65, 65, 0, 'Buah', 'Baik', 'Lemari 3 / 4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (37, '', 'Tabung Reaksi', 'Sedang', 'Alat Bahan Kaca', 'Tidak Berskala', 48, 48, 2, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 4', 'A,C', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (38, '', 'Tabung Reaksi', 'Biasa', 'Alat Bahan Kaca', 'Tidak Berskala', 111, 111, 9, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 4', 'A,D', '9 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (39, '', 'Tabung Reaksi', 'Besar', 'Alat Bahan Kaca', 'Tidak Berskala', 19, 19, 3, 'Buah', 'Sebagian Rusak', 'Lemari 3 / 4', 'B', '3 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (40, 'KPP 16', 'Pipa Kaca', '40 cm', 'Alat Bahan Kaca', 'Tidak Berskala', 5, 5, 0, 'Buah', 'Baik', 'Lemari 3 / 4', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (41, 'KPP 16', 'Pipa Kapiler J', 'Buah', 'Alat Bahan Kaca', 'Tidak Berskala', 3, 3, 0, 'Buah', 'Baik', 'Lemari 9/2', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (42, 'BMK 90/075', 'Kaca Pembesar (LUP)', '75 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 12, 12, 0, 'Buah', 'Baik', 'Lemari 9/2', 'D,E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (43, 'BMK 90/021', 'Kaca Pembesar (LUP)', '21 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 3, 3, 0, 'Buah', 'Baik', 'Lemari 9/2', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (44, 'BMK 90/010', 'Kaca Pembesar (LUP)', '10 mm', 'Alat Bahan Kaca', 'Tidak Berskala', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/2', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (45, 'BMK 62', 'Kaca Benda', 'Dos', 'Alat Bahan Kaca', 'Tidak Berskala', 12, 12, 3, 'Dos', 'Sebagian Rusak', 'Lemari 9/3', 'A,C', '3 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (46, 'BMK 72/016', 'Kaca Penutup', 'Pak', 'Alat Bahan Kaca', 'Tidak Berskala', 10, 10, 5, 'Pak', 'Sebagian Rusak', 'Lemari 9/3', 'A,B', '5 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (47, 'BPG 48', 'Jala plankton', 'Sedang', 'Alat Plastik, Kayu & Besi', 'Umum', 0, 0, 1, 'Buah', 'Rusak', 'Lemari 2/1', 'A', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (48, 'BPG 55', 'Jala serangga', 'Sedang', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lemari 2/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (49, 'BPG 65', 'Perangkap serangga', 'Sederhana', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lemari 2/1', 'A/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (50, 'KKA 55', 'Kaki Tiga', 'Tungku', 'Alat Plastik, Kayu & Besi', 'Umum', 16, 16, 0, 'Buah', 'Baik', 'Lemari 3/1', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (51, '', 'Kasa', 'Plat', 'Alat Plastik, Kayu & Besi', 'Umum', 52, 52, 0, 'Buah', 'Baik', 'Lemari 3/1', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (52, '', 'Papan Bedah', 'Plat', 'Alat Plastik, Kayu & Besi', 'Umum', 20, 20, 0, 'Buah', 'Baik', 'Lemari 3/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (53, 'KTA 90', 'Rak Tabung Reaksi', 'Kayu', 'Alat Plastik, Kayu & Besi', 'Umum', 12, 12, 0, 'Buah', 'Baik', 'Lemari 3/1', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (54, 'KTA 92', 'Rak Tabung Reaksi', 'Plastik', 'Alat Plastik, Kayu & Besi', 'Umum', 8, 8, 0, 'Buah', 'Baik', 'Lemari 3/1', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (55, 'KIM 25/080', 'Lumpung dan alu, q 10 cm', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 21, 21, 0, 'Set', 'Baik', 'Lemari 3/2', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (56, '', 'Plat Tetes', '12 Lubang', 'Alat Plastik, Kayu & Besi', 'Umum', 12, 12, 0, 'Buah', 'Baik', 'Lemari 3/2', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (57, 'KSK 24', 'Sikat Tabung', 'Tabung Reaksi', 'Alat Plastik, Kayu & Besi', 'Umum', 21, 21, 0, 'Buah', 'Baik', 'Lemari 3/3', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (58, 'KSK 24', 'Sikat Tabung', 'Buret', 'Alat Plastik, Kayu & Besi', 'Umum', 8, 8, 0, 'Buah', 'Baik', 'Lemari 3/3', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (59, 'KTA 85', 'Penjepit Tabung', 'Kayu', 'Alat Plastik, Kayu & Besi', 'Umum', 14, 14, 0, 'Buah', 'Baik', 'Lemari 3/3', 'A,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (60, 'KTA 85', 'Penjepit Tabung', 'Besi', 'Alat Plastik, Kayu & Besi', 'Umum', 3, 3, 0, 'Buah', 'Baik', 'Lemari 3/3', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (61, '', 'Auksanometer', 'Besar', 'Alat Plastik, Kayu & Besi', 'Umum', 0, 0, 5, 'Buah', 'Rusak', 'Atas Lemari 3', 'C', '5 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (62, '', 'Batang Statif', 'sedang', 'Alat Plastik, Kayu & Besi', 'Umum', 7, 7, 0, 'Buah', 'Baik', 'Atas Lemari 3', 'A,B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (63, 'BMK 36', 'Mikroskop sterio', 'Biasa', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lemari 6/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (64, 'BMK 24', 'Mikroskop lanjutan', 'Dua penggerak', 'Alat Plastik, Kayu & Besi', 'Umum', 5, 5, 0, 'Buah', 'Baik', 'Lemari 6/2', 'A /C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (65, 'BMK 15', 'Mikroskop Siswa', 'EPS 400', 'Alat Plastik, Kayu & Besi', 'Umum', 24, 20, 11, 'Buah', 'Sebagian Rusak', 'Lemari 6/2,3', 'A,C', '11 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (66, 'BPG 29', 'Quadrat  Folding', 'Bongkar Pasang', 'Alat Plastik, Kayu & Besi', 'Umum', 10, 10, 0, 'Pasang', 'Baik', 'Lemari 9/1', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (67, 'BMK 79', 'Storage Case Plastic', 'Plat', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (68, '', 'Dissecting Dish', 'Plat', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (69, 'BFS 96', 'Kotak Genetik', 'Hukum Mendel', 'Alat Plastik, Kayu & Besi', 'Umum', 8, 8, 0, 'Buah', 'Baik', 'Lemari 9/2', 'B,C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (70, 'BMK 48', 'Perangkat pemeliharaan  Mikroskop', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 3, 3, 0, 'Set', 'Baik', 'Lemari 9/2', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (71, 'BPB 42', 'Sphygmomanometer', 'Air Raksa dan Biasa', 'Alat Plastik, Kayu & Besi', 'Umum', 4, 4, 2, 'Buah', 'Sebagian Rusak', 'Lemari 9/2', 'B,D,E', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (72, 'BPG 41', 'Steteskop', 'Buah', 'Alat Plastik, Kayu & Besi', 'Umum', 9, 9, 1, 'Buah', 'Sebagian Rusak', 'Lemari 9/2', 'B,D,E', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (73, 'BPS 68', 'Higrometer', 'Jenis putar', 'Alat Plastik, Kayu & Besi', 'Umum', 6, 6, 4, 'Buah', 'Sebagian Rusak', 'Lemari 9/2', 'A', '4 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (74, '', 'Jarum Spoit', 'Spoit Kaca', 'Alat Plastik, Kayu & Besi', 'Umum', 19, 19, 0, 'Buah', 'Baik', 'Lemari 9/2', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (75, 'KA 31', 'Crucible', 'Cawang10 mm', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lemari 9/2', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (76, '', 'Timbangan Digital', 'KD 200', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/2', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (77, '', 'Stan Baterai', '2 Baterai', 'Alat Plastik, Kayu & Besi', 'Umum', 14, 14, 0, 'Buah', 'Baik', 'Lemari 9/3', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (78, '', 'Stan Baterai', '4 Baterai', 'Alat Plastik, Kayu & Besi', 'Umum', 6, 6, 0, 'Buah', 'Baik', 'Lemari 9/3', 'C,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (79, '', 'Kabel Penghubung', '30 cm', 'Alat Plastik, Kayu & Besi', 'Umum', 11, 11, 11, 'Buah', 'Sebagian Rusak', 'Lemari 9/3', 'A,B', '11 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (80, 'KST 34', 'Klem Buret', 'Ganda', 'Alat Plastik, Kayu & Besi', 'Umum', 4, 4, 0, 'Buah', 'Baik', 'Lemari 9/3', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (81, 'KST 34', 'Klem Universal', 'Tunggal', 'Alat Plastik, Kayu & Besi', 'Umum', 8, 8, 6, 'Buah', 'Sebagian Rusak', 'Lemari 9/3', 'A,B', '6 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (82, '', 'Auksanometer', 'Kecil', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/3', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (83, 'KSM 19', 'Sumbat Karet', '2 lbg 35/27', 'Alat Plastik, Kayu & Besi', 'Umum', 4, 4, 0, 'Buah', 'Baik', 'Lemari 9/3', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (84, 'KSM 8.06', 'Alat pelubang gabus', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 7, 7, 0, 'Set', 'Baik', 'Lemari 9/4', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (85, 'KSM 10', 'Pengasah pelubang gabus', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 6, 6, 0, 'Set', 'Baik', 'Lemari 9/4', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (86, 'KTA 100', 'Alat pemusing', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Set', 'Baik', 'Lemari 9/4', 'C/D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (87, 'BPB 01', 'Pinset', 'Alat  Bedah', 'Alat Plastik, Kayu & Besi', 'Umum', 27, 27, 0, 'Buah', 'Baik', 'Lemari 9/4', 'D,F', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (88, '', 'Gunting Bedah', 'Lurus Ujung Lancip', 'Alat Plastik, Kayu & Besi', 'Umum', 4, 4, 0, 'Buah', 'Baik', 'Lemari 9/4', 'D,F', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (89, '', 'Blood lancet', 'Dos', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Dos', 'Baik', 'Lemari 9/4', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (90, '', 'Blood lancet otomatis', 'Buah', 'Alat Plastik, Kayu & Besi', 'Umum', 6, 6, 0, 'Buah', 'Baik', 'Lemari 9/4', 'C,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (91, '', 'Slaid', 'Dos', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Dos', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (92, '', 'Tangkai Skalpel', 'No 3', 'Alat Plastik, Kayu & Besi', 'Umum', 14, 14, 0, 'Buah', 'Baik', 'Lemari 9/4', 'D,F', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (93, 'BMK 78', 'Hard mikrotom', 'Sederhana', 'Alat Plastik, Kayu & Besi', 'Umum', 9, 9, 0, 'Buah', 'Baik', 'Lemari 9/4', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (94, '', 'Pisau Bedah', 'Alat Bedah', 'Alat Plastik, Kayu & Besi', 'Umum', 10, 10, 8, 'Buah', 'Sebagian Rusak', 'Lemari 9/5', 'A,D', '8 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (95, 'BPB 40.001', 'Perangkat alat bedah', 'Set', 'Alat Plastik, Kayu & Besi', 'Umum', 12, 12, 2, 'Set', 'Sebagian Rusak', 'Lemari 9/5', 'A,B', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (96, '', 'Neraca Ohauz', '311 gr', 'Alat Plastik, Kayu & Besi', 'Umum', 7, 7, 0, 'Buah', 'Baik', 'Atas Lemari 9', 'A,B,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (97, '', 'Mikroskop Elektron', 'XSZ-107BN', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lemari 10', 'E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (98, 'BPG 67', 'Akuarium', '30x20x20', 'Alat Plastik, Kayu & Besi', 'Umum', 3, 3, 0, 'Buah', 'Baik', 'Lab Biologi', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (99, 'BPG 67/02-75', 'Akuarium plexy glass', '60x30x32', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lab Biologi', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (100, '', 'Alat Pemadam', 'Penyemprot', 'Alat Plastik, Kayu & Besi', 'Umum', 3, 3, 0, 'Buah', 'Baik', 'Lab Biologi', 'A,D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (101, '', 'Kompor Hook', '22 sumbu', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (102, '', 'Panci ( dandang)', '5 liter', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (103, '', 'Kompor Gas', '2 Mata', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'G', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (104, '', 'Panci Steamer', '5 liter', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (105, '', 'Alat Ukur Tinggi Badan', '200 cm', 'Alat Plastik, Kayu & Besi', 'Umum', 1, 1, 0, 'Buah', 'Baik', 'Lab Biologi', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (106, 'BPG 01', 'Timbangan Badan', 'Biasa', 'Alat Plastik, Kayu & Besi', 'Umum', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'D,F', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (107, 'BMD 44', 'Model mata manusia', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 6/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (108, 'BMD 49', 'Model telinga', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 0, 'Buah', 'Baik', 'Lemari 6/1', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (109, 'BMD 59', 'Model jantung manusia', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 6/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (110, 'BMD 81.01', 'Model hati', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 0, 'Buah', 'Baik', 'Lemari 6/1', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (111, 'BMD 81.03', 'Model lambung', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 0, 'Buah', 'Baik', 'Lemari 6/1', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (112, 'BMD 72', 'Model manusia', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 2, 'Buah', 'Sebagian Rusak', 'Atas Lemari 6', 'A', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (113, 'BMD 81.04', 'Model lidah dan gigi', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Atas Lemari 6', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (114, 'BMS 45. 17', 'Cardiac Musclec', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Atas Lemari 6', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (115, 'BMD 05', 'Model hidung', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Atas Lemari 6', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (116, 'BMD 40', 'Model ginjal manusia', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Atas Lemari 6', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (117, 'BMD 40', 'Model otak manusia', 'Alat peraga', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Atas Lemari 6', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (118, 'VCB 12', 'DNA dan RNA', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (119, 'VCB 40.001', 'Sistem transportasi', 'Set', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Set', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (120, 'VCB 40.002', 'Sistem pencernaan', 'Set', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Set', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (121, 'VCB  40.005', 'Sistem koordinasi', 'Set', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Set', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (122, 'VCB 53. 02', 'Otot', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (123, 'VCB 53. 03', 'Sistem saraf', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 0, 0, 1, 'Buah', 'Rusak', 'Lemari 9/1', 'A', '1 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (124, 'VCB 53. 04', 'Peredaraan darah', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (125, 'VCB 53. 05', 'Pencernan', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (126, 'VCB 53.06', 'Eskresi', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (127, 'VCB 53.07', 'Pernapasan manusia', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (128, 'VCB 53.01', 'Rangka Tubuh Manusia', 'Gbr. Dinding', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lemari 9/1', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (129, 'BMK 32.01', 'Lilium kotak sari', 'Profase awal', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (130, 'BMK 32.02', 'Lilium kotak sari', 'Profase akhir', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (131, 'BMK 32.03', 'Lilium kotak sari', 'Metafase', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (132, 'BMK 32.04', 'Lilium kotak sari', 'Profase akhir', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (133, 'BMK 33.02', 'Jamur mucor', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (134, 'BMK 33.01', 'Kotak spora paku', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (135, 'BMK 33.03', 'Amuba', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (136, 'BMK 33.04', 'Hydra', 'Utuh', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (137, 'BMS  33.05', 'Cacing hati', 'Dewasa utuh', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (138, 'BMS 33.06', 'Cacing hati', 'Larva', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (139, 'BMS 38.01', 'Polysiphonia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (140, 'BMS 38.03', 'Polysiphonia WM', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (141, 'BMS 38.04', 'Helianthus sp', 'Akar mudah', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (142, 'BMS 38.06', 'Zea mays', 'Akar', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (143, 'BMS 38.07', 'Zea mays', 'Batang', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Batang', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (144, 'BMS 38.08', 'Zea mays', 'Daun', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (145, 'BMS 38.09', 'Cucurbita', 'Batang', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Batang', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (146, 'BMS 38.11', 'Ficus', 'Daun', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (147, 'BMS 38.12', 'Asparagus', 'Daun', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (148, 'BMS 45. 01', 'Ribbone marrow', 'Daun', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (149, 'BMS 45. 04', 'Otot lurik', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (150, 'BMS 45. 05', 'Otot polos', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (151, 'BMS 45. 07', 'Sel hati mamalia', 'Liver', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (152, 'BMS 45. 09', 'Colom mamalia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (153, 'BMS 45. 10', 'Trachea mamalia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (154, 'BMS 45. 11', 'Kulit manusia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (155, 'BMS 45. 12', 'Kelenjar testis mamalia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (156, 'BMS 45. 13', 'Kelenjar ovarium mamalia', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (157, 'BMS 45. 14', 'Adrenal glend', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (158, 'BMS 45. 15', 'Ginjal', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (159, 'BMS 45. 16', 'Sel saraf', 'Preparat', 'Media Pembelajaran & Preparat', 'Preparat / Model', 10, 10, 0, 'Buah', 'Baik', 'Lemari 9/4', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (160, 'BMH 918', 'Model hidung dan lida', '2 Dimensi', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lab Biologi', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (161, 'BMH 921', 'Model mitosis', '2 Dimensi', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (162, 'BMH 922', 'Model meiosis', '2 Dimensi', 'Media Pembelajaran & Preparat', 'Preparat / Model', 2, 2, 0, 'Buah', 'Baik', 'Lab Biologi', 'B/C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (163, 'BMM 81 / 13', 'Model perkembangan janin manusia', '2 Dimensi', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 0, 'Buah', 'Baik', 'Lab Biologi', 'C', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (164, 'BMD 80', 'Rangka Manusi', 'Medium', 'Media Pembelajaran & Preparat', 'Preparat / Model', 1, 1, 2, 'Buah', 'Sebagian Rusak', 'Lab Biologi', 'A,B', '2 unit kondisi rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (165, 'LA', 'Lemari kayu penyimpanan alat', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 1, 'Unit', 'Sebagian Rusak', 'Bagian Belakang', 'A', '1 unit rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (166, 'LA', 'Lemari kaca penyimpanan alat', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 3, 3, 0, 'Unit', 'Baik', 'Bagian Belakang', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (167, 'LM', 'Lemari Mikroskop', 'Kayu jati/Kaca', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 0, 'Unit', 'Baik', 'Samping Kanan Mejah Guru', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (168, 'LZ', 'Lemari zat', 'Kayu jati', 'Aset Prasarana', 'Furnitur & Ruang', 2, 2, 0, 'Unit', 'Baik', 'Bagian Belakang', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (169, 'LA', 'Lemari kaca', 'Kaca', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 0, 'Unit', 'Baik', 'Ruang Istirah Guru', 'E', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (170, 'MP', 'Meja praktek', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 0, 0, 0, 'Unit', 'Baik', 'Ruang Praktek', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (171, 'MD', 'Meja Demonstrasi / Meja Guru', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 0, 'Unit', 'Baik', 'Ruang Praktek', 'A', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (172, 'MG', 'Meja guru', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 2, 2, 0, 'Unit', 'Baik', 'Ruang Praktek', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (173, 'KG', 'Kursi guru', 'Jati', 'Aset Prasarana', 'Furnitur & Ruang', 3, 3, 0, 'Unit', 'Baik', 'Ruang Praktek', 'D', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (174, 'KS', 'Kursi siswa', 'Plastik', 'Aset Prasarana', 'Furnitur & Ruang', 25, 25, 6, 'Unit', 'Sebagian Rusak', 'Ruang Praktek', 'B', '6 unit rusak');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (175, 'KS', 'Kursi siswa', 'Bulat (Besi)', 'Aset Prasarana', 'Furnitur & Ruang', 22, 22, 0, 'Unit', 'Baik', 'Ruang Praktek', 'G', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (176, 'KK', 'Kotak P3K', 'Kayu', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 0, 'Unit', 'Baik', 'Ruang Istirah Guru', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (177, 'LP', 'Kulkas', 'Satu Pintu', 'Aset Prasarana', 'Furnitur & Ruang', 1, 1, 0, 'Unit', 'Baik', 'Ruang Istirah Guru', 'B', '');
INSERT INTO barang (id, kode_barang, nama_barang, spesifikasi, kategori, sub_kategori, stok_total, stok_tersedia, stok_rusak, satuan, kondisi, lokasi_penyimpanan, sumber_dana, keterangan) VALUES (178, 'BP', 'Baju Pratikum', 'Lembar', 'Aset Prasarana', 'Furnitur & Ruang', 38, 38, 0, 'Lembar', 'Baik', 'Lemari 9', 'B', '');
SELECT setval('barang_id_seq', (SELECT MAX(id) FROM barang));

INSERT INTO peminjaman (id, nomor_formulir, barang_id, nama_peminjam, kelas_jabatan, keperluan, jumlah, tanggal_pinjam, tanggal_rencana_kembali, tanggal_kembali_aktual, kondisi_saat_pinjam, kondisi_saat_kembali, status, keterangan) VALUES (1, 'FP-2026/08/001', 4, 'HJ. Haslinda, S.Pd.', 'Guru Biologi', 'Praktikum Uji Makanan (Kelas XI MIPA 1)', 5, '2026-08-13', '2026-08-14', '2026-08-14', 'Baik', 'Baik', 'dikembalikan', 'Lengkap dan dikembalikan dalam kondisi bersih');
INSERT INTO peminjaman (id, nomor_formulir, barang_id, nama_peminjam, kelas_jabatan, keperluan, jumlah, tanggal_pinjam, tanggal_rencana_kembali, tanggal_kembali_aktual, kondisi_saat_pinjam, kondisi_saat_kembali, status, keterangan) VALUES (2, 'FP-2026/09/002', 65, 'Rini Rahmayani Sjam, S.Pd, M.Pd', 'Guru Biologi / Kepala Lab', 'Pengamatan Jaringan Daun Siswa Kelas XII MIPA 2', 4, '2026-09-02', '2026-09-05', NULL, 'Baik', NULL, 'dipinjam', 'Dipinjam 4 unit mikroskop siswa untuk meja kelompok 1-4');
SELECT setval('peminjaman_id_seq', (SELECT MAX(id) FROM peminjaman));

INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (1, 'peminjaman', 4, 1, 'Peminjaman 5 unit "Gelas Kimia 250 ml" oleh HJ. Haslinda, S.Pd. (Keperluan: Praktikum Uji Makanan)', 'Juni Aswati, S.Si', '2026-09-03 10:54:15');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (2, 'pengembalian', 4, 1, 'Pengembalian 5 unit "Gelas Kimia 250 ml" oleh HJ. Haslinda, S.Pd. Kondisi: Baik', 'Juni Aswati, S.Si', '2026-09-03 10:54:15');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (3, 'peminjaman', 65, 2, 'Peminjaman 4 unit "Mikroskop Siswa" oleh Rini Rahmayani Sjam, S.Pd, M.Pd (Kelas XII MIPA 2)', 'Juni Aswati, S.Si', '2026-09-03 10:54:15');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (4, 'import_csv', NULL, NULL, 'Inisialisasi Import Data: 178 barang laboratorium berhasil dimuat dari data inventaris resmi SMAN 1 Pinrang TA 2026/2027.', 'Juni Aswati, S.Si', '2026-09-03 10:54:15');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (5, 'tambah_barang', NULL, NULL, 'Penambahan barang baru: "Respirometer Ganong Eksperimen Model Standar Biologi" (Stok: 5 Set, Lokasi: Lemari 4 / 2)', 'Juni Aswati, S.Si (Laboran Lab Biologi)', '2026-09-03 11:03:58');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (6, 'peminjaman', NULL, 3, 'Peminjaman 2 Set "Respirometer Ganong Eksperimen Model Standar Biologi" oleh Drs. H. Amran, M.Pd (Guru Biologi). Rencana kembali: 2026-09-04', 'Juni Aswati, S.Si (Laboran Lab Biologi)', '2026-09-03 11:03:58');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (7, 'pengembalian', NULL, 3, 'Pengembalian 2 unit "Respirometer Ganong Eksperimen" oleh Drs. H. Amran, M.Pd. Kondisi: Baik. Catatan: Dikembalikan lengkap dan bersih', 'Juni Aswati, S.Si (Laboran Lab Biologi)', '2026-09-03 11:03:58');
INSERT INTO log_riwayat (id, jenis_aktivitas, barang_id, peminjaman_id, deskripsi, admin_name, waktu) VALUES (8, 'hapus_barang', NULL, NULL, 'Penghapusan barang: "Respirometer Ganong Eksperimen Model Standar Biologi" (ID: 179) oleh Admin.', 'Juni Aswati, S.Si (Laboran Lab Biologi)', '2026-09-03 11:03:58');
SELECT setval('log_riwayat_id_seq', (SELECT MAX(id) FROM log_riwayat));

